@serverURL = http://localhost:3000

@token = {{login.response.body.token}}

@username = {{user.response.body.user.username}}

### login
# @name login
POST {{serverURL}}/users/login
Content-Type: application/json

{
    "email": "jani@gmail.com",
    "password": "Titkosjelszo123"
}

### register
POST {{serverURL}}/users/registration
Content-Type: application/json

{
    "username": "Jani",
    "email": "jani@gmail.com",
    "password": "Titkosjelszo123",
    "confirm": "Titkosjelszo123"
}

### get user's profile
# @name user
GET {{serverURL}}/users/profile/Jani
Content-Type: application/json
Authorization: Bearer {{token}}

### follow user by username
POST {{serverURL}}/users/follow/Jani
Content-Type: application/json
Authorization: Bearer {{token}}

### get user's followers by username
POST {{serverURL}}/users/followers/Jani
Content-Type: application/json
Authorization: Bearer {{token}}

### get user's followed by user's username
POST {{serverURL}}/users/followed/Jani
Content-Type: application/json
Authorization: Bearer {{token}}

### 
POST {{serverURL}}/users/toggleban/Jani2
Content-Type: application/json
Authorization: Bearer {{token}}