@serverURL = http://localhost:3000

@token = {{login.response.body.token}}

### login
# @name login

POST {{serverURL}}/users/login
Content-Type: application/json

{
    "email": "jani@gmail.com",
    "password": "Titkosjelszo123"
}

### register

POST {{serverURL}}/users/registration
Content-Type: application/json

{
    "username": "Jani",
    "email": "jani@gmail.com",
    "password": "Titkosjelszo123",
    "confirm": "Titkosjelszo123"
}